scan_config:
  enabled: true
  update_branch_format: "release-update/{0}"
  labels:
    - release-update
  pr_reviewers:
    - epam-avramenko
#    - folio-org/acquisitions

release_branches:
  - R2-2025