scan_config:
  enabled: true
  update_branch_format: "release-update/{0}"
  labels:
    - release-scan
    - auto-update
  pr_reviewers:
#    - eldiiar-duishenaliev
    - epam-avramenko
#    - OHaimanov
#    - folio-org/kitfox
#    - folio-org/acquisitions

release_branches:
  - R1-2025
  - R2-2024
  - R2-2025