name: Update Snapshot Application

run-name: Application Release Branch Preparation ${{ github.event_name == 'schedule' && '[scheduled]' || '' }}

on:
  schedule:
    - cron: "*/20 * * * *"

  workflow_dispatch:
    inputs:
      descriptor_build_offset:
        description: 'Offset to apply to application artifact version'
        required: false
        type: string
        default: '100100000000000'
      rely_on_FAR:
        description: 'Whether to rely on FAR for application descriptor dependencies'
        required: false
        type: boolean
        default: false
      dry_run:
        description: 'Perform dry run without making changes'
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  update-application:
    name: Update Application
    uses: folio-org/kitfox-github/.github/workflows/app-update.yml@RANCHER-2321-test #TODO: Switch to master before PR merge
    with:
      app_name: ${{ github.event.repository.name }}
      repo: ${{ github.repository }}
      workflow_run_number: ${{ github.run_number }}
      descriptor_build_offset: ${{ github.event_name == 'workflow_dispatch' && inputs.descriptor_build_offset || '100100000000000' }}
      rely_on_FAR: ${{ github.event_name == 'workflow_dispatch' && inputs.rely_on_FAR || false }}
      dry_run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}
    secrets: inherit

  slack_notification:
    name: Slack Notification
    needs: update-application
    if: always() && 
      (needs.update-application.result != 'success' || 
        needs.update-application.result == 'success' && needs.update-application.outputs.updated == 'true') && 
      vars.SLACK_NOTIF_CHANNEL != '' # && (github.event_name == 'workflow_dispatch' && inputs.dry_run || false) TODO: Add this condition before merging 
    uses: folio-org/kitfox-github/.github/workflows/app-update-notification.yml@RANCHER-2321-test #TODO: Switch to master before PR merge
    with:
      app_name: ${{ github.event.repository.name }}
      repo: ${{ github.repository }}
      new_version: ${{ needs.update-application.outputs.new_version }}
      previous_version: ${{ needs.update-application.outputs.previous_version }}
      updated_cnt: ${{ needs.update-application.outputs.updated_cnt }}
      updated_modules: ${{ needs.update-application.outputs.updated_modules }}
      updated_modules_b64: ${{ needs.update-application.outputs.updated_modules_b64 }}
      failure_reason: ${{ needs.update-application.outputs.failure_reason }}
      commit_sha: ${{ needs.update-application.outputs.commit_sha }}
      workflow_result: ${{ needs.update-application.result }}
      workflow_run_id: ${{ github.run_id }}
      workflow_run_number: ${{ github.run_number }}
      slack_notif_channel: ${{ vars.SLACK_NOTIF_CHANNEL }}
    secrets: inherit
