name: Application Release Scan

run-name: Application Release Scan ${{ github.event_name == 'schedule' && '[scheduled]' || '' }}

on:
  schedule:
    - cron: "*/20 * * * *"
  
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Perform dry run without creating PRs'
        required: false
        type: boolean
        default: false

concurrency:
  group: release-scan-${{ github.repository }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  get-branches:
    name: Determine Branches
    uses: folio-org/kitfox-github/.github/workflows/app-release-scan-get-branches.yml@RANCHER-2323-test #TODO: Change to master when ready
    with:
      config_file: '.github/release-scan-config.yml'

  scan-branches:
    name: Scan ${{ matrix.branch }}
    needs: get-branches
    if: needs.get-branches.outputs.branch_count > 0
    strategy:
      matrix:
        branch: ${{ fromJson(needs.get-branches.outputs.branches) }}
      fail-fast: false
      max-parallel: 3
    uses: ./.github/workflows/app-release-scan-single-branch.yml
    with:
      release_branch: ${{ matrix.branch }}
      dry_run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}
      pr_reviewers: ${{ needs.get-branches.outputs.pr_reviewers }}
    secrets: inherit